__include__: [
  '../dataset/custom_detection.yml',
  '../runtime.yml',
  '../base/dataloader.yml',
  '../base/optimizer.yml',
  '../base/dfine_hgnetv2.yml',
  '../base/rtv4.yml'
]

output_dir: C:/Users/WYZ/Desktop/cotton/rtdetrv4_baseline/outputs/rtv4_hgnetv2_s_cotton
summary_dir: C:/Users/WYZ/Desktop/cotton/rtdetrv4_baseline/outputs/rtv4_hgnetv2_s_cotton/tensorboard

num_classes: 21
remap_mscoco_category: False

HGNetv2:
  name: 'B0'
  return_idx: [1, 2, 3]
  freeze_at: -1
  freeze_norm: False
  use_lab: True
  pretrained: True
  local_model_dir: ./pretrain/hgnetv2/

HybridEncoder:
  in_channels: [256, 512, 1024]
  hidden_dim: 256
  depth_mult: 0.34
  expansion: 0.5
  distill_teacher_dim: 0

DFINETransformer:
  num_layers: 3
  eval_idx: -1

epoches: 50
flat_epoch: 29
no_aug_epoch: 8
checkpoint_freq: 5
print_freq: 50
use_amp: True
use_ema: False
sync_bn: False

optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.0001
    -
      params: '^(?=.*backbone)(?=.*norm|bn).*$'
      lr: 0.0001
      weight_decay: 0.
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn|bias)).*$'
      weight_decay: 0.
  lr: 0.0002
  betas: [0.9, 0.999]
  weight_decay: 0.0001

RTv4Criterion:
  weight_dict: {loss_mal: 1, loss_bbox: 5, loss_giou: 2, loss_fgl: 0.15, loss_ddf: 1.5}
  losses: ['mal', 'boxes', 'local']
  gamma: 1.5
  reg_max: 32
  matcher:
    type: HungarianMatcher
    weight_dict: {cost_class: 2, cost_bbox: 5, cost_giou: 2}
    alpha: 0.25
    gamma: 2.0

train_dataloader:
  dataset:
    img_folder: C:/Users/WYZ/Desktop/cotton/cotton_rtdetr_dataset/images/train
    ann_file: C:/Users/WYZ/Desktop/cotton/rtdetrv4_baseline/data/cotton_coco_zero_based/annotations/instances_train.json
    transforms:
      policy:
        epoch: [4, 29, 45]
  total_batch_size: 8
  num_workers: 2
  drop_last: True
  collate_fn:
    base_size: 640
    base_size_repeat: 3
    mixup_epochs: [4, 29]
    stop_epoch: 45

val_dataloader:
  dataset:
    img_folder: C:/Users/WYZ/Desktop/cotton/cotton_rtdetr_dataset/images/val
    ann_file: C:/Users/WYZ/Desktop/cotton/rtdetrv4_baseline/data/cotton_coco_zero_based/annotations/instances_val.json
  total_batch_size: 16
  num_workers: 2
  drop_last: False

